### ISSUE TITLE
Add option to hide iframe scrollbars

### ISSUE THREAD

**Issue by nbremer** [gcalmettes/reveal.js-d3#12]
Using a background visualization that is set to use the entire window creates scrollbars in the iframe for me because it's just a little too wide and high then, which I don't want to see. (Maybe it comes from using the `external` plugin as well?) Could there perhaps be an option that sets the `scrolling="no"` [attribute](https://www.w3schools.com/tags/att_iframe_scrolling.asp) on the iframe?

(I've now implemented a simple `data-scroll` extra option in the local copy I have of the `reveald3.js` code, which works, but I thought it might be a nice addition generally :) )

**Comment by gcalmettes** [comment]
Hey @nbremer!

Thanks for the suggestion! A new `data-scroll` optional attribute has been added (See merged PR https://github.com/gcalmettes/reveal.js-d3/pull/13). It is set to `yes` by default. 

I have updated the documentation with a new [advanced configuration](https://github.com/gcalmettes/reveal.js-d3#advanced-configuration-of-the-embedded-iframe) section, and I have added a slide in the demo deck showing the `data-scroll='no'` in action.

Let me know if you need any other options or things that should be improved.
