### ISSUE TITLE
iframe height is too small on firefox

### ISSUE THREAD

**Issue by Fil** [gcalmettes/reveal.js-d3#3]
here I highlight the dimensions of the iframe:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/7001/33352111-a32b5ddc-d4a7-11e7-9107-d4c87055c28b.png">

we can fix this by using width=100vw and height=100vh on iframe elements, but this belongs upstream to reveal.js I guess (?) https://github.com/gcalmettes/reveal.js-d3/blob/master/demo/reveal.js/js/reveal.js#L3164

**Comment by gcalmettes** [comment]
The plugin creates an iframe element for each visualization, so I should be able to fix it on my end. I made the change in https://github.com/gcalmettes/reveal.js-d3/commit/547dde419958ee71a6576bf54d819d88b086e39b . Thanks @Fil !
