### ISSUE TITLE
Div off centered until manually resize window

### ISSUE THREAD

**Issue by wnowak10** [gcalmettes/reveal.js-d3#5]
When I include:

`<section>
			    <div class="fig-container"
			         data-file="plugin/reveald3/demo/d3-fig/eclipses.html"></div> 
				</section>`

The eclipse visualization loads partially off screen. When I resize the Chrome (or Safari) window, the viz shifts to center of the screen, as expected. 

Any ideas what's wrong?

**Comment by gcalmettes** [comment]
Can you include a screenshot so I better see what problem you're confronted with?

**Comment by mattgodbolt** [comment]
I get this too, if I have a `<div>` that doesn't have a size associated with it. If I start on the page containing the d3 integration it's ok, but if I navigate away and then back it's off-centre, until I resize the window.

It's fixed if I force the size of the `<div>` tag.

**Comment by mattgodbolt** [comment]
Attached is a screencast demonstrating what I see if I disable the div sizings:

[Screencast.zip](https://github.com/gcalmettes/reveal.js-d3/files/2065287/Screencast.zip)

* Starts out ok on the d3 slide
* Going back ("to "1 bit of dynamic RAM")
* Going forward to the d3 slide shows the div's size is not being taken into account; it's as if d3 hasn't recomputed the size of the div
* Resizing the view, all is OK
* Runs through the presentation, and then goes to next slide
* Goes back, d3 div is in wrong spot again
* Reloading page, fixes it.

**Comment by gcalmettes** [comment]
Thanks for the screencast.

So you mean that 

```
<section>
    <h3>My title</h3>
    <div class="fig-container"  data-file="path/to/the/file.html"></div>
</section>
```

will cause the problem but as soon as you set a size to the `div` tag like 

```
<section>
    <h3>My title</h3>
    <div width="100%" class="fig-container"  data-file="path/to/the/file.html"></div>
</section>
```

that prevents the problem to happen?

**Comment by mattgodbolt** [comment]
Specifically the height needs to be set and it seems to need to be an absolute value. `height=100%` doesn't work.

**Comment by gcalmettes** [comment]
I'll try to reproduce the issue and look into a fix.

Last question, does the problem happen whatever browser you are using?

Thanks!

**Comment by mattgodbolt** [comment]
I tested both Firefox (60.0.1) and Chrome (67.0.3396.62) on Linux (which is all I have to test with). Thanks in advance!

**Comment by gcalmettes** [comment]
@wnowak10 @mattgodbolt did you guys publish some slides where the problem occur?

I tried starting from a fresh `reveal.js` folder, just adding the plugin (`version 1.4.3`) and inserting the exact slide @wnowak10 posted (when opening the issue) as well as other slides with d3 visualizations inserted, but I was unable to reproduce the problem.

I am on macOS High Sierra and tried on Chrome (Version 67.0.3396.87 (Official Build) (64-bit)), Chrome Canary (Version 69.0.3457.0 (Official Build) canary (64-bit)) and Safari (Version 11.1.1 (13605.2.8)).
Would love to be able to reproduce the problem so I can investigate an fix it.

**Comment by AffeAli** [comment]
@wnowak10 @mattgodbolt The issue is fixed for me with this [patch](https://gist.github.com/AffeAli/95a811a619c3bd8649caa8d9a88837e3).

**Comment by gcalmettes** [comment]
Thanks @AffeAli!
@wnowak10 @mattgodbolt I have added the patch (see f1d200a00a66230e02b04e5c616567d338c55178), can you confirm that this solve the problem you were seeing?
