### ISSUE TITLE
iframe embed doesn't work on IE 11

### ISSUE THREAD

**Issue by richielionell** [gcalmettes/reveal.js-d3#7]
https://gcalmettes.github.io/reveal.js-d3/demo/#/ - The demo works well on Chrome & Firefox but for some reason the iframe embed doesn't display on IE 11

**Comment by gcalmettes** [comment]
It looks like this is a known issue with certain version of IE11.
I have added a `<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE11">` tag in the html of the demo. Could you try again and see if this work now? (I have only access to a mac).

Another solution would be to run IE11 in compatibility mode (see [the official instructions](https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-v)).

**Comment by richielionell** [comment]
Still doesn't work. Should something be tweaked in lib/js/head.min.js ?

**Comment by gcalmettes** [comment]
Well, the head.min.js is provided by reveal.js so I wouldn't mess around this. Not sure how to go around this if the `<meta>` tag above doesn't work, as it seems to be IE11 specific.
